package models

const bun = `
// Code generated by sql-to-go; DO NOT EDIT.

package models

import (
{{- range $column := $.Columns }}
	{{- if hasPrefix "time" $column.Type }}
	"time"
	{{- end }}
{{- end }}

	"github.com/uptrace/bun"
)

type {{ camelcase $.Name }} struct {
	bun.BaseModel ` + "`" + `bun:"table:{{ $.Name }}"` + "`" + `

	{{- range $key, $column := $.Columns }}
		{{ camelcase $key | replace "Id" "ID" }} {{ if not $column.NotNull }}*{{ end }}{{ $column.Type }}  ` + "`" + `bun:"{{ $key }},{{ $column.Options | join "," }}"` + "`" + `
	{{- end }}

	{{- range $reference := $.References }}
		{{ camelcase $reference }} *{{ camelcase $reference }} ` + "`" + `bun:"rel:belongs-to"` + "`" + `
	{{- end }}


	{{- range $key, $table := $.Result.Tables }}
		{{- range $reference := $table.References }}
			{{- if eq $reference $.Name }}
				{{- if $.References.Contain $reference }}
					{{ camelcase $key }} *{{ camelcase $key }} ` + "`" + `bun:"rel:has-one"` + "`" + `
				{{- else }}
					{{ camelcase $key }}s []*{{ camelcase $key }} ` + "`" + `bun:"rel:has-many"` + "`" + `
				{{- end }}
			{{- end }}
		{{- end }}
	{{- end }}
}
`
