package models

const bun = `
// Code generated by sql-to-go; DO NOT EDIT.

package dbmodels

import (
{{- range $column := .Columns }}
	{{- if hasPrefix "time" $column.Type }}
	"time"
	{{- end }}
{{- end }}

	"github.com/uptrace/bun"
)

type {{ camelcase .Name }} struct {
	bun.BaseModel ` + "`" + `bun:"table:{{ .Name }}"` + "`" + `

	{{- range $column := .Columns }}
		{{- if eq $column.Name "id" }}
		ID
		{{- else }}
		{{ camelcase $column.Name }}
		{{- end }} {{ if $column.Null }}*{{ end }}{{ $column.Type }}
	{{- end }}
}
`
